name: Show Context Variables

on: [push]

jobs:
  show-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show github.ref
        run: echo "github.ref: ${{ github.ref }}"

      - name: Show github.repository
        run: echo "github.repository: ${{ github.repository }}"
